shell: Add missing sys/time.h include
Fixes the following build failure:

```
penberg@turing:~/src/penberg/limbo-eval/Mobibench/shell$ make
gcc -o mobibench mobibench.c sqlite3.c -lpthread -ldl -DNDEBUG=1 -DHAVE_USLEEP=1 -DSQLITE_HAVE_ISNAN -DSQLITE_THREADSAFE=2 -DSQLITE_TEMP_STORE=3 -DSQLITE_POWERSAFE_OVERWRITE=1 -DSQLITE_DEFAULT_FILE_FORMAT=4 -DSQLITE_DEFAULT_AUTOVACUUM=1 -DSQLITE_ENABLE_MEMORY_MANAGEMENT=1 -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_BACKWARDS -DSQLITE_ENABLE_FTS4 -DSQLITE_OMIT_BUILTIN_TEST -DSQLITE_OMIT_COMPILEOPTION_DIAGS -DSQLITE_OMIT_LOAD_EXTENSION -DSQLITE_DEFAULT_FILE_PERMISSIONS=0666 -DUSE_PREAD64 --static
mobibench.c: In function ‘get_current_utime’:
mobibench.c:1667:9: error: implicit declaration of function ‘gettimeofday’; did you mean ‘SYS_gettimeofday’? [-Wimplicit-function-declaration]
 1667 |         gettimeofday(&current,NULL);
      |         ^~~~~~~~~~~~
      |         SYS_gettimeofday
make: *** [Makefile:40: all] Error 1
```